---
sidebar: sidebar 
permalink: reference-new.html 
keywords: new features, release notes, enhancements 
summary: O Cloud Volumes ONTAP 9.11.0 inclui uma nova melhoria. 
---
= Novidades do Cloud Volumes ONTAP 9.11.0
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Cloud Volumes ONTAP 9.11.0 inclui uma nova melhoria.

Recursos e aprimoramentos adicionais também são introduzidos nas versões mais recentes do BlueXP . Consulte https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Notas de versão do BlueXP"^] para obter detalhes.



== Suporte para volumes elásticos (7 de junho de 2022)

O suporte ao recurso volumes elásticos do Amazon EBS com um agregado Cloud Volumes ONTAP fornece melhor desempenho e capacidade adicional, ao mesmo tempo que permite que o BlueXP  aumente automaticamente a capacidade de disco subjacente conforme necessário.

O suporte para volumes elásticos está disponível a partir da versão 3.9.19 do conetor BlueXP  e é suportado com versões Cloud Volumes ONTAP específicas e tipos de disco EBS específicos.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Saiba mais sobre o suporte para volumes elásticos"^]



== 9.11.0 P1 (2 de maio de 2022)

A versão do Cloud Volumes ONTAP 9.11.0 P1 já está disponível na AWS, Azure e Google Cloud. Esta versão inclui a seguinte melhoria.



=== Suporte ao ONTAP S3 na AWS

Agora você pode fornecer storage de objetos S3 da Cloud Volumes ONTAP na AWS (o Microsoft Azure já é compatível). O Cloud Volumes ONTAP oferece suporte ao S3 como opção para storage com escalabilidade horizontal, além de protocolos clássicos baseados em arquivos, como NFS e SMB.

Observe o seguinte:

* O principal caso de uso do ONTAP S3 com Cloud Volumes ONTAP é um armazenamento de objetos de uso geral.
* Neste momento, o protocolo S3 não é compatível com o Cloud Volumes ONTAP no Google Cloud.
* O BlueXP  não fornece recursos de gerenciamento para o recurso ONTAP S3.


https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Saiba como configurar e gerenciar serviços de armazenamento de objetos S3 no ONTAP"^].



== Notas de atualização

Leia estas notas para saber mais sobre a atualização para esta versão.



=== Como atualizar

As atualizações do Cloud Volumes ONTAP devem ser concluídas a partir do BlueXP . Você não deve atualizar o Cloud Volumes ONTAP usando o Gerenciador de sistema ou a CLI. Isso pode afetar a estabilidade do sistema.

http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Saiba como atualizar quando o BlueXP  o notificar"^].



=== Caminho de atualização suportado

Você pode atualizar para o Cloud Volumes ONTAP 9.11.0 a partir da versão 9.10.1. A BlueXP  solicitará que você atualize os sistemas Cloud Volumes ONTAP qualificados para esta versão.



=== Versão necessária do conetor

O conetor BlueXP  deve estar executando a versão 3.9.18 ou posterior para atualizar os sistemas existentes para 9.11.0.


TIP: As atualizações automáticas do conetor são ativadas por padrão, portanto, você deve estar executando a versão mais recente.



=== Tempo de inatividade

* A atualização de um sistema de nó único leva o sistema off-line por até 25 minutos, durante os quais a e/S é interrompida.
* A atualização de um par de HA não causa interrupções e e/S é ininterrupta. Durante esse processo de atualização sem interrupções, cada nó é atualizado em conjunto para continuar fornecendo e/S aos clientes.




=== Atualizações na AWS com tipos de instância C4, M4 e R4 EC2

Na AWS, os tipos de instância C4, M4 e R4 EC2 não são mais compatíveis com novas implantações do Cloud Volumes ONTAP. Se você tiver um sistema existente que esteja sendo executado em um tipo de instância C4, M4 ou R4, será necessário alterar para um tipo de instância na família de instâncias C5, M5 ou R5. Se você não puder alterar o tipo de instância, será necessário habilitar a rede aprimorada antes de atualizar.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html#upgrades-in-aws-with-c4-m4-and-r4-ec2-instance-types["Saiba como atualizar na AWS com os tipos de instância C4, M4 e R4 EC2"^]. link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Saiba como alterar o tipo de instância EC2 para Cloud Volumes ONTAP"^].

link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Suporte à NetApp"^]Consulte para saber mais sobre o fim da disponibilidade e suporte para esses tipos de instância.
